name: Test Build *Nix

on:
  workflow_call:

jobs:
  test-build-nix:
    name: Test binary compilation for all platforms:arch
    runs-on: ubuntu-latest
    env:
      TAG: "v0.0.0"
    steps:
      - uses: actions/checkout@v4
      - name: Build all platforms:arch
        run: make ci/build
