name: Integration Tests on *Nix

on:
  workflow_call:

jobs:
  test-integration-nix:
    name: Run integration tests on *Nix
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Integration test
        run: make integration-test
