name: Build and Push Builder Image

on:
  push:
    branches:
      - main
      - master
      - feat/fips-image-and-workflow # for testing purposes

jobs:
  build-and-push:
    name: Build and Push Builder Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version
        id: set_version
        run: |
          VERSION="${{ github.run_number }}-$(date +'%Y%m%d%H%M%S')"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: build/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ env.VERSION }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
