on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 5 * * *'  # Everyday at 05:00

jobs:
  reposettings:
    name: Apply GH repo settings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read reposettings.yml
        run: |
          echo 'REPOSETTINGS_YML<<EOF' >> $GITHUB_ENV
          cat reposettings.yml >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: txqueuelen/reposettings@eae1df5886c9b3a818fc2a8a1ca695d6186ead83
        with:
          github_token: ${{ secrets.COREINT_BOT_TOKEN }}
          config: ${{ env.REPOSETTINGS_YML }}
